/*
 * DA.live Block Library generator for sports-emotion-storefront.
 *
 * Generates the Document Authoring "library" content that powers the
 * draggable Blocks/Templates sidebar in DA. Unlike the Universal Editor
 * models (component-definition/models/filters.json), the DA Block Library is
 * NOT auto-generated by Edge Delivery — it consumes sheets + example documents
 * under a `library/` folder, exactly like Adobe's `aem-boilerplate` /
 * `aem-block-collection` do.
 *
 * This script derives all of that from the existing `component-definition.json`
 * so we do not have to author ~40 documents by hand.
 *
 * Output:
 *   library/blocks.json               sheet `blocks`  (name + path)
 *   library/templates.json            sheet `templates` (key + value)
 *   library/blocks/<name>.html        example block doc (HTML, not ignored by .hlxignore)
 *   library/templates/<slug>.html     reusable page templates (PDP, Page, Landing)
 *
 * The example docs are emitted as .html because this repo's .hlxignore ignores
 * *.md, which would prevent DA from fetching the block markup; .html passes
 * through Edge Delivery unmodified.
 *
 * The sheets use the EDS "multi-sheet JSON" shape that DA's da-library client
 * reads via getSheetByName()/getFirstSheet().
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..', '..');

// ---- Project identity (override via env if different) -------------------------
const ORG = process.env.LIBRARY_ORG || 'hiberus-magento';
const SITE = process.env.LIBRARY_SITE || 'sports-emotion-storefront';

// The DA Library block/template `path` must be an absolute content.da.live URL:
// DA's getBlockVariants() fetches the path directly (no host normalization), and
// a relative path would resolve against the da.live editor origin and 404.
const contentUrl = (p) => `https://content.da.live/${ORG}/${SITE}/${p}`;

// ---- Which blocks are exposed as draggable content blocks --------------------
// Exclusion rules: transactional commerce blocks, global chrome, primitives,
// sectioning and child-items. These are not "drag into the page" content.
const EXCLUDE = new Set([
  'header', 'footer', 'modal',
  'section', 'text', 'image', 'page-metadata',
  'accordion-item', 'card', 'carousel-item', 'columns-row', 'columns-cell',
]);

function isChildItem(id) {
  return /-(item|row|cell)$/.test(id);
}

function isEditable(id) {
  if (EXCLUDE.has(id)) return false;
  if (id.startsWith('commerce-')) return false;
  if (isChildItem(id)) return false;
  return true;
}

// ---- Read the merged component definition ------------------------------------
const definition = JSON.parse(
  readFileSync(join(ROOT, 'component-definition.json'), 'utf8'),
);

// Collect editable blocks with their DA plugin config.
const blocks = [];
for (const group of definition.groups || []) {
  for (const component of group.components || []) {
    const id = component.id;
    const da = component.plugins?.da || {};
    if (isEditable(id)) {
      blocks.push({ id, title: component.title, da });
    }
  }
}

// Sort alphabetically by title for a predictable library.
blocks.sort((a, b) => a.title.localeCompare(b.title));

// ---- Example document body per block type ------------------------------------
// DA's da-library parses the example doc and looks for <main> > div > .block-name
// (see getBlockVariants). We emit a full HTML block page so the markup survives
// the *.md ignores in .hlxignore (this repo deliberately does not serve .md).
function esc(text) {
  return String(text).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

// Human descriptions per block, surfaced in DA's Library via the "Library
// Metadata" table (info icon). Keyed by block id. Any block not listed here
// falls back to a generic description.
const BLOCK_DESCRIPTIONS = {
  accordion: 'Acordeón con ítems desplegables para agrupar contenido en poco espacio.',
  cards: 'Tarjetas en cuadrícula para presentar contenido, imágenes o enlaces destacados.',
  carousel: 'Carrusel de diapositivas para mostrar banners, imágenes o promociones.',
  columns: 'Distribución de contenido en varias columnas para estructurar la página.',
  enrichment: 'Contenido reutilizable inyectado por producto o categoría (bloque contextual).',
  fragment: 'Fragmento de contenido reutilizado en varias páginas desde una única fuente.',
  hero: 'Banner de cabecera con imagen y título principal para secciones destacadas.',
  'product-details': 'Bloque de detalle de producto: nombre, precio, imágenes y compra.',
  'product-list-page': 'Listado de productos con filtros y paginación.',
  'product-recommendations': 'Carousel de recomendaciones de productos para la ficha.',
  'targeted-block': 'Contenido dirigido a segmentos o grupos de clientes específicos.',
};

function blockExampleHtml(block) {
  const { da } = block;
  const kind = da.type === 'key-value-block' ? 'keyvalue' : da.behaviour === 'columns' ? 'columns' : 'table';
  const className = da.name || block.id;
  const title = block.title;

  let rows;
  if (kind === 'keyvalue') {
    rows = [['key', 'value']];
  } else if (kind === 'columns') {
    rows = [['Column A', 'Column B']];
  } else {
    const cols = da.columns || 2;
    const n = da.rows || 1;
    rows = Array.from({ length: n }, () => Array.from({ length: cols }, () => 'Texto'));
  }

  const body = rows
    .map((cells) => `      <div>${cells.map((c) => `<div>${esc(c)}</div>`).join('')}
      </div>`)
    .join('\n');

  // Library Metadata table (optional per da.live guide) — gives the block an
  // "info" icon + description in DA. DA reads the sibling element with class
  // library-metadata for `description`/`searchtags` (helpers/index.js transformBlock).
  const description = BLOCK_DESCRIPTIONS[block.id]
    || 'Bloque de contenido editable insertable desde la librería de DA.';

  return `<!DOCTYPE html>
<html><head><title>${esc(title)}</title></head>
<body>
  <main>
    <div class="section">
      <div class="${className}">
${body}
      </div>
      <div class="library-metadata">
        <div><div>Description</div><div>${esc(description)}</div></div>
      </div>
    </div>
  </main>
</body>
</html>
`;
}

// ---- Generate the EDS sheet JSON ---------------------------------------------
function sheetJson(sheetName, rows) {
  return {
    ':type': 'multi-sheet',
    ':names': [sheetName],
    [sheetName]: {
      ':type': 'sheet',
      ':sheetname': sheetName,
      data: rows,
    },
  };
}

function writeJSON(file, obj) {
  writeFileSync(file, JSON.stringify(obj, null, 2).concat('\n'), 'utf8');
}

function writeHTML(file, content) {
  writeFileSync(file, content, 'utf8');
}

// ---- Build all the artefacts -------------------------------------------------
const libraryDir = join(ROOT, 'library');
const blocksDir = join(libraryDir, 'blocks');
const templatesDir = join(libraryDir, 'templates');
mkdirSync(blocksDir, { recursive: true });
mkdirSync(templatesDir, { recursive: true });

// 1) library/blocks.json — sheet `blocks`
const blockRows = blocks.map((b) => ({
  name: b.title,
  path: contentUrl(`library/blocks/${b.id}`),
}));
writeJSON(join(libraryDir, 'blocks.json'), sheetJson('blocks', blockRows));

// 2) Example documents per block
for (const block of blocks) {
  writeHTML(join(blocksDir, `${block.id}.html`), blockExampleHtml(block));
}

// 3) library/templates.json — sheet `templates` (key + value)
const templates = [
  { slug: 'pdp', key: 'Producto (PDP)', value: contentUrl('library/templates/pdp') },
  { slug: 'pagina', key: 'Página', value: contentUrl('library/templates/pagina') },
  { slug: 'landing', key: 'Landing', value: contentUrl('library/templates/landing') },
];
writeJSON(
  join(libraryDir, 'templates.json'),
  sheetJson('templates', templates.map(({ key, value }) => ({ key, value }))),
);

function templateHtml(title, blockNames) {
  const rows = blockNames
    .map((b) => `      <div class="section"><div>${esc(b)}</div></div>`)
    .join('\n');
  return `<!DOCTYPE html>
<html><head><title>${esc(title)}</title></head>
<body>
  <main>
${rows}
  </main>
</body>
</html>
`;
}

// 4) Template documents
writeHTML(
  join(templatesDir, 'pdp.html'),
  templateHtml('Producto (PDP)', ['Enrichment', 'Product Details', 'Product Recommendations']),
);
writeHTML(
  join(templatesDir, 'pagina.html'),
  templateHtml('Página', ['Hero', 'Columns', 'Cards']),
);
writeHTML(
  join(templatesDir, 'landing.html'),
  templateHtml('Landing', ['Hero', 'Carousel', 'Cards', 'Accordion']),
);

// NOTE: no fstab.yaml is emitted. This repo is a code (not Drive-mounted)
// project; the HTML example docs under /library are served directly by Edge
// Delivery through passthrough, without a drive mountpoint. Adding an fstab
// mount could override the Code-Sync-managed content, so we leave it out.

// ---- Summary -------------------------------------------------------------
console.log(`Generated DA library for ${ORG}/${SITE}`);
console.log(`  editable blocks: ${blocks.length}`);
blocks.forEach((b) => console.log(`    - ${b.title} (${b.id})`));
console.log('  templates:', templates.map((t) => t.key).join(', '));
console.log('');
console.log('Next steps:');
console.log(`  1. Review/overwrite the path of each block in library/blocks.json`);
console.log(`     if you want content URLs other than content.da.live defaults.`);
console.log(`  2. Configure DA (da.live/sheet#/${ORG}/${SITE}/.da/config) with:`);
console.log('     key              | value');
console.log(`     library-blocks   | ${ORG}/${SITE}/library/blocks`);
console.log(`     library-templates| ${ORG}/${SITE}/library/templates`);
console.log('  3. Commit, push and let AEM Code Sync publish the content.');